#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Post-Consensus Junction Refinement for RECTIFY

For every N-op (intron skip) in every consensus read, this module tests all
candidate junctions within a search radius and selects the best-supported one
using a split-alignment scoring approach with homopolymer-aware edit distance.

Motivation:
    Aligners sometimes place splice junctions imprecisely — a few bp off from
    the true exon/intron boundary, or at a non-canonical GT-AG site when a
    nearby canonical one exists.  Because the consensus step picks the "best"
    aligner for each read independently, the chosen aligner may have placed
    an N-op with slightly wrong boundaries.

    This step normalises all N-op boundaries to the best-supported candidate
    junction by scoring each option using a split-alignment: the query sequence
    window around the current N-op split point is tested against every candidate
    junction's genomic context, with the split point allowed to slide ±max_slide
    query bases to account for boundary absorption errors.

Scoring priority (lower tuple = better):
    1. score_bin:      floor(score) when current junction is non-canonical,
                       raw float otherwise.  Non-canonical junctions with clear
                       sequence evidence (≥ 1.0 edit difference) always win;
                       sub-integer differences (within HP noise floor) are
                       resolved by canonical tier.
    2. canonical_tier: 0 = GT+AG (both canonical), 1 = one canonical, 2 = neither
                       — active when current junction is non-canonical (tier ≥ 4)
                       so canonical alternatives win in the noise floor
    3. is_alt:         0 if candidate matches the current N-op boundaries exactly,
                       1 otherwise — when current is canonical, ties favour the
                       existing junction to avoid spurious displacement
    4. annotated:      0 = junction in annotated set, 1 = novel
                       — tie-breaker; annotation never overrides clear evidence
    5. abs_delta:      prefer smallest boundary shift from current N-op

Algorithm:
    For each N-op [ns, ne) in a read, with query split point q_split:
    1. Collect all candidate junctions [js, je) within search_radius
    2. For each candidate [js, je), try all k in [0, len(rescue) - 1]:
         t1(k) = _score_hp_anchored(rescue[k:],       g[je    : je+buf])   # intron_end-anchored
         t2(k) = _score_hp_anchored(rescue[:k][::-1], g[je-buf: je  ][::-1])  # intron_end-proximal
         score(k) = t1(k) + t2(k)
    3. Best score for this candidate = min_k score(k)
    4. Select overall best by (score_bin, canonical_tier/is_alt, annotated, abs_delta)
    5. If the winner differs from the current N-op, replace it in the CIGAR

    Bilateral scoring (t1+t2) ensures all rescue bases are accounted for.
    t2 prevents degenerate short-suffix matches (e.g. 1-char rescue at k=L-1)
    from scoring 0.0 via coincidence, without any candidate pre-filtering.

    No candidate guards are applied.  All candidates from the junction pool are
    scored and the best wins.  Non-canonical, novel junctions can win if sequence
    evidence is clear (≥ 1.0 edit difference over the canonical alternative).

Module layout:
    The scoring + scoring-table layers live in peer modules:

    * ``hp_penalty``       — HpPenaltyTable, _hp_edit_distance, the numba DP
                             kernel, _hp_run_length, _str_repeat_info,
                             _precompute_del_costs.
    * ``junction_scoring`` — canonicality, junction-pool plumbing, the
                             _score_hp_anchored / _score_junction scoring
                             kernels, plus the CIGAR-op constants reused below.

    This module holds the refinement orchestrator: per-read N-op iteration
    (``refine_read_junctions``), CIGAR surgery (``_apply_junction_replacement``),
    and the sequential / parallel BAM-driver loops
    (``refine_bam_junctions``, ``_run_sequential``, ``_run_parallel``).

    The names tests import directly from this module
    (``_canonical_tier``, ``_hp_edit_distance``, ``_score_junction``,
    ``build_junction_pool``, ``_build_junction_index``, ``_candidates_near``,
    plus ``HpPenaltyTable`` and ``_hp_run_length`` for external callers) are
    re-exported below so downstream code does not need to follow the move.

Empirical Penalty Tables
------------------------
By default, `_score_hp_anchored` and `_hp_edit_distance` use heuristic costs:
    del(HP=1)  = 1.0,  del(HP≥4) = 0.5,  ins = 1.25
These are replaced by base-class-specific, monotone-isotonic empirical costs when
a ``penalty_scores.tsv`` is provided via ``--junction-penalty-table``.  The table
is generated by ``common/scripts/nanopore/empirical_cigar_error_profiler.py`` run
over all 16 aligner chunks for a dataset.  Key differences from the heuristic:

    HP=8 A/T del cost ≈ 0.13   (heuristic: 0.50)   — much more permissive
    HP=8 C/G del cost ≈ 0.77   (heuristic: 0.50)   — much more conservative
    HP=1 non-STR del cost ≈ 0.58  (heuristic: 1.0)

An optional ``str_penalty_scores.tsv`` (``--str-penalty-table``) provides STR
(dinucleotide/trinucleotide repeat) slippage costs keyed by (unit, n_copies),
loaded alongside the HP table via ``HpPenaltyTable.from_tsv(path, str_path=...)``.

To regenerate tables for a new dataset (all 16 chunks, ~30–60 min):

    python common/scripts/nanopore/empirical_cigar_error_profiler.py \\
        --run-dir <dev_run_dir> \\
        --reference software/rectify/rectify/data/S288C_reference_sequence_R64-5-1_20240529.fsa \\
        --output-dir <out_dir> \\
        --isolation-flank 10 --union --str-repeat

Then pass the outputs to rectify::

    rectify correct ... \\
        --junction-penalty-table <out_dir>/penalty_scores.tsv \\
        --str-penalty-table      <out_dir>/str_penalty_scores.tsv

The most recent pre-built tables live in:
    common/scripts/nanopore/error_profile_<date>/penalty_scores.tsv
    common/scripts/nanopore/error_profile_<date>/str_penalty_scores.tsv

Author: Kevin R. Roy
Email: kevinrjroy@gmail.com
Date: 2026-04-20
"""

from __future__ import annotations

import json
import logging
import os
import time
from collections import Counter, defaultdict
from pathlib import Path
from typing import Dict, Iterator, List, Optional, Set, Tuple

import pysam

from ...utils.genome import standardize_chrom_name

# CIGAR-op constants and the Junction type alias live in junction_scoring so
# scoring kernels and this orchestrator share a single source of truth.
from .junction_scoring import (
    Junction,
    _CANONICAL_HP_PRIOR,
    _D,
    _EQ,
    _H,
    _I,
    _M,
    _N,
    _QUERY_CONSUMING,
    _REF_CONSUMING,
    _REF_CONSUMING_POS,
    _S,
    _X,
    _build_junction_index,
    _candidates_near,
    _canonical_tier,
    _score_junction,
    build_junction_pool,
)

# Re-exports for backwards compatibility with external callers / tests that
# import these names from rectify.core.splice.junction_refiner.
from .hp_penalty import (  # noqa: F401
    HpPenaltyTable,
    _hp_edit_distance,
    _hp_run_length,
)
from .junction_scoring import (  # noqa: F401
    _NUMBA_AVAILABLE,
    _score_hp_anchored,
)

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Annotated-canonical evidence gate (edit-distance units)
# ---------------------------------------------------------------------------
# Read evidence a candidate must have OVER an annotated + canonical incumbent
# before Module 2H will move the junction somewhere that is not both annotated
# and canonical.  1.0 = one full edit-distance unit, i.e. the sub-integer HP
# noise floor named in refine_read_junctions' scoring policy: below that, the
# difference between two placements is homopolymer noise, not evidence.
# Set RECTIFY_ANNOT_CANON_HOLD=0 to restore the pre-2026-09 behaviour (any
# score win, however small, could move an annotated GT-AG onto a novel
# non-canonical junction).
_ANNOTATED_CANONICAL_HOLD: float = float(
    os.environ.get("RECTIFY_ANNOT_CANON_HOLD", "1.0")
)


class JunctionRefineProfile:
    """Low-overhead aggregate profiler for Module 2H junction refinement."""

    def __init__(self, sample_rate: int = 1) -> None:
        self.sample_rate = max(1, int(sample_rate or 1))
        self.timings: Counter[str] = Counter()
        self.counts: Counter[str] = Counter()
        self.candidate_hist: Counter[int] = Counter()
        self.candidate_after_cap_hist: Counter[int] = Counter()

    def add_time(self, key: str, seconds: float) -> None:
        self.timings[key] += float(seconds)

    def inc(self, key: str, n: int = 1) -> None:
        self.counts[key] += int(n)

    def observe_candidates(self, n: int, *, after_cap: bool = False) -> None:
        hist = self.candidate_after_cap_hist if after_cap else self.candidate_hist
        hist[int(n)] += 1

    def merge(self, other: Optional[object]) -> None:
        if other is None:
            return
        if isinstance(other, JunctionRefineProfile):
            other = other.to_raw_dict()
        if not isinstance(other, dict):
            return
        self.timings.update({k: float(v) for k, v in other.get('timings', {}).items()})
        self.counts.update({k: int(v) for k, v in other.get('counts', {}).items()})
        self.candidate_hist.update({
            int(k): int(v) for k, v in other.get('candidate_hist', {}).items()
        })
        self.candidate_after_cap_hist.update({
            int(k): int(v) for k, v in other.get('candidate_after_cap_hist', {}).items()
        })

    def to_raw_dict(self) -> dict:
        return {
            'sample_rate': self.sample_rate,
            'timings': dict(self.timings),
            'counts': dict(self.counts),
            'candidate_hist': dict(self.candidate_hist),
            'candidate_after_cap_hist': dict(self.candidate_after_cap_hist),
        }

    @staticmethod
    def _percentiles(hist: Counter[int]) -> dict:
        total = sum(hist.values())
        if total <= 0:
            return {'n': 0, 'min': None, 'p50': None, 'p90': None, 'p99': None, 'max': None}
        items = sorted(hist.items())

        def pct(q: float) -> int:
            threshold = max(1, int((q * total) + 0.999999))
            seen = 0
            for value, count in items:
                seen += count
                if seen >= threshold:
                    return value
            return items[-1][0]

        return {
            'n': total,
            'min': items[0][0],
            'p50': pct(0.50),
            'p90': pct(0.90),
            'p99': pct(0.99),
            'max': items[-1][0],
        }

    def to_summary(self) -> dict:
        total_time = sum(self.timings.values())
        timing_percent = {
            k: (100.0 * v / total_time if total_time > 0 else 0.0)
            for k, v in self.timings.items()
        }
        return {
            'version': 1,
            'sample_rate': self.sample_rate,
            'counts': dict(sorted(self.counts.items())),
            'timings_seconds': dict(sorted(self.timings.items())),
            'timings_percent_of_profiled_time': dict(sorted(timing_percent.items())),
            'candidate_count_summary': self._percentiles(self.candidate_hist),
            'candidate_count_after_cap_summary': self._percentiles(
                self.candidate_after_cap_hist
            ),
            'candidate_hist': {str(k): v for k, v in sorted(self.candidate_hist.items())},
            'candidate_after_cap_hist': {
                str(k): v for k, v in sorted(self.candidate_after_cap_hist.items())
            },
        }


def _profile_time(profile: Optional[JunctionRefineProfile], key: str, start: float) -> None:
    if profile is not None:
        profile.add_time(key, time.perf_counter() - start)


def _rank_and_cap_candidates(
    candidates: List[Tuple[int, int]],
    chrom: str,
    ns: int,
    ne: int,
    annotated_set: Set[Junction],
    max_candidates: Optional[int],
) -> List[Tuple[int, int]]:
    """Deterministically rank candidates and cap the scoring set when requested."""
    if not max_candidates or max_candidates <= 0 or len(candidates) <= max_candidates:
        return candidates

    current = (ns, ne)

    def rank(item: Tuple[int, int]) -> Tuple[int, int, int, int, int, int]:
        js, je = item
        is_current = 0 if item == current else 1
        is_annotated = 0 if (chrom, js, je) in annotated_set else 1
        boundary_delta = abs(js - ns) + abs(je - ne)
        length_delta = abs((je - js) - (ne - ns))
        return (is_current, is_annotated, boundary_delta, length_delta, js, je)

    return sorted(candidates, key=rank)[:max_candidates]

__all__ = [
    # Re-exported from hp_penalty for backwards compatibility
    'HpPenaltyTable',
    '_hp_edit_distance',
    '_hp_run_length',
    # Re-exported from junction_scoring for backwards compatibility
    '_canonical_tier',
    '_score_junction',
    '_score_hp_anchored',
    'build_junction_pool',
    '_build_junction_index',
    '_candidates_near',
    # Native to this module
    'refine_read_junctions',
    '_apply_junction_replacement',
    '_apply_replacements_to_read',
    '_iter_n_ops',
    '_has_boundary_error',
    'refine_bam_junctions',
    'evaluate_hp_pen_values',
    'PenaltyTableSet',
]


# ---------------------------------------------------------------------------
# Per-UMI-bin penalty table set
# ---------------------------------------------------------------------------

class PenaltyTableSet:
    """Maps per-read UMI-count tag to the appropriate :class:`HpPenaltyTable`.

    Used for protocols where error rates vary with UMI cluster depth (e.g. ONT
    PCR-cDNA with UMI consensus).  The ``umi_tag`` (default ``XC``) is read
    from each BAM record; the count is bucketed into ``umi1`` / ``umi2`` /
    ``umi3plus`` bins.  If the tag is absent or the bin is not in ``bins``,
    the lookup falls back to the ``pooled`` entry.

    Example::

        tables = {
            'umi1':    HpPenaltyTable.from_tsv(path_umi1),
            'umi2':    HpPenaltyTable.from_tsv(path_umi2),
            'umi3plus': HpPenaltyTable.from_tsv(path_umi3plus),
            'pooled':  HpPenaltyTable.from_tsv(path_pooled),
        }
        pts = PenaltyTableSet(tables)
        effective_table = pts.for_read(read)
    """

    def __init__(
        self,
        bins: Dict[str, 'HpPenaltyTable'],
        umi_tag: str = 'XC',
    ) -> None:
        self.bins = bins
        self.umi_tag = umi_tag
        self._fallback: Optional['HpPenaltyTable'] = bins.get('pooled')

    def for_read(self, read: 'pysam.AlignedSegment') -> Optional['HpPenaltyTable']:
        """Return the table for *read* based on its UMI-count tag value."""
        try:
            count = int(read.get_tag(self.umi_tag))
        except (KeyError, TypeError):
            return self._fallback
        if count == 1:
            return self.bins.get('umi1', self._fallback)
        if count == 2:
            return self.bins.get('umi2', self._fallback)
        return self.bins.get('umi3plus', self._fallback)


# ---------------------------------------------------------------------------
# Per-read N-op refinement
# ---------------------------------------------------------------------------

def _iter_n_ops(
    read: pysam.AlignedSegment,
) -> Iterator[Tuple[int, int, int, int]]:
    """Yield (cigar_idx, ref_start, ref_end, q_split) for each N-op.

    q_split = number of query-consuming bases consumed before this N-op,
    counting only bases from aligned (reference-consuming) regions and their
    adjacent soft-clips.  Leading H/S ops are excluded; trailing S at the 5'
    RNA end (right side for is_reverse reads) are included after the last
    ref-consuming op.

    H ops never appear in query_sequence and are always skipped.
    S ops at the start of the CIGAR (before any reference-consuming op) are
    leading soft-clips and do NOT count toward q_split.
    S ops after at least one ref-consuming op (trailing in genomic terms) DO
    count toward q_split.

    The genomic cursor advances on ``_REF_CONSUMING_POS`` (M/D/=/X **and N**):
    an intron consumes reference, so a walker that skipped it reported every
    N-op after the first short by the summed length of the preceding introns
    (ISSUE-004).
    """
    q_pos = 0
    r_pos = read.reference_start
    seen_ref_op = False   # True once at least one ref-consuming op has been processed

    for i, (op, length) in enumerate(read.cigartuples):
        if op == _H:
            continue  # H never in query_sequence; skip entirely
        if op == _N:
            yield i, r_pos, r_pos + length, q_pos
        if op in _REF_CONSUMING_POS:
            r_pos += length
        if op in _REF_CONSUMING:
            # q_split semantics unchanged: a leading soft-clip is one that
            # precedes the first ALIGNED op, so N does not open the alignment.
            seen_ref_op = True
        if op in _QUERY_CONSUMING and op != _S:
            q_pos += length
        elif op == _S:
            # Count soft-clip only if we have already seen a reference-consuming op
            # (i.e., this is NOT a leading soft-clip)
            if seen_ref_op:
                q_pos += length


def _has_boundary_error(
    cigartuples: List[Tuple[int, int]],
    intron_start: int,
    intron_end: int,
    ref_start: int,
    window: int,
) -> bool:
    """Return True if there is an X (mismatch) or I/D (indel) op within
    *window* reference bases of either the intron_start or intron_end boundary.

    This is used as a pre-filter for junction refinement: only reads with
    alignment evidence of a boundary problem (noisy bases near the splice site)
    benefit from re-scoring; clean M-op alignments indicate the aligner was
    already confident.

    Args:
        cigartuples:  Read CIGAR tuples.
        intron_start: Left boundary of the N-op (0-based).
        intron_end:   Right boundary of the N-op (0-based, exclusive).
        ref_start:    Read reference_start.
        window:       Reference distance from either boundary to search.

    Returns:
        True if any X, I, or D op falls within *window* bp of intron_start or
        intron_end; False otherwise.
    """
    if not cigartuples:
        return False

    # Ops of interest: X (mismatch), I (insertion), D (deletion)
    _error_ops = frozenset([_D, _I, _X])
    _ref_ops   = frozenset([_M, _D, _EQ, _X])  # ops that advance ref pos

    ref_pos = ref_start
    for op, length in cigartuples:
        if op == _H:
            continue
        if op == _N:
            ref_pos += length
            continue
        if op in _error_ops:
            # The reference span of this op is [ref_pos, ref_pos + ref_len)
            ref_len = length if op in _ref_ops else 0
            op_end  = ref_pos + ref_len  # exclusive

            # Check proximity to intron_start
            if ref_pos <= intron_start + window and op_end >= intron_start - window:
                return True
            # Check proximity to intron_end
            if ref_pos <= intron_end + window and op_end >= intron_end - window:
                return True
        if op in _ref_ops:
            ref_pos += length
        # S/I: don't advance ref

    return False


# Only the four real DNA bases can constitute a homopolymer run or a microhomology
# match; a shared ambiguity code (N) or non-ACGT symbol must NOT (audit A5).
_ACGT = frozenset("ACGT")


def _hp_run_across(seq: str, pos: int, min_run: int) -> int:
    """If a junction boundary at *pos* (between ``seq[pos-1]`` and ``seq[pos]``) sits
    INSIDE a reference homopolymer run — same base on both sides — return that run's
    length; otherwise 0.

    This is the HP-drift-guard detector.  Ubiquitous ONT homopolymer undercalls let
    an evidence-only re-placer slide a junction boundary *within* a run (re-parti-
    tioning identical bases between intron and exon) — fabricating a false
    non-canonical junction.  A move that lands a boundary inside a run (this returns
    >0) is required to clear a stronger evidence margin; a move to a genuine sequence
    TRANSITION (``seq[pos-1] != seq[pos]`` → 0 here), e.g. a real non-canonical
    acceptor, is untouched.  So motif-blind discovery is preserved everywhere except
    the one spot ubiquitous undercalls make the evidence untrustworthy."""
    n = len(seq)
    if pos <= 0 or pos >= n:
        return 0
    b = seq[pos]
    if b not in _ACGT:
        return 0                    # ambiguity/non-ACGT (N) run is NOT a homopolymer
    if b != seq[pos - 1]:
        return 0                    # boundary is a sequence transition, not in a run
    i = pos - 1
    while i > 0 and seq[i - 1] == b:
        i -= 1
    j = pos
    while j < n - 1 and seq[j + 1] == b:
        j += 1
    run = j - i + 1
    return run if run >= min_run else 0


def _frac_match(a: str, b: str) -> float:
    """Fraction of positions where equal-length strings *a* and *b* agree (0.0 if
    empty or mismatched length).

    Only ACGT bases can MATCH: a shared ambiguity code (N==N, or lowercase/non-ACGT)
    is NOT counted as agreement.  Genome ambiguity runs (N…N, gaps) would otherwise
    score frac 1.0 → a phantom microhomology that falsely vetoes a genuine move
    (audit A5).  x==y with x in _ACGT ⇒ both are the same real base."""
    if not a or len(a) != len(b):
        return 0.0
    return sum(1 for x, y in zip(a, b) if x == y and x in _ACGT) / len(a)


def _move_microhomology(seq: str, ns: int, ne: int, js: int, je: int) -> float:
    """Microhomology-drift-guard detector (the general, non-homopolymer analog of
    ``_hp_run_across``).

    For a candidate junction move ``(ns, ne) -> (js, je)`` that shifts the donor
    and/or acceptor by ``k`` bp, return the FRACTION of the shifted ``k``-mer that
    REPEATS at the drift distance — i.e. how much local microhomology (a near-tandem
    direct repeat) makes the ``k``-bp boundary drift near-tied by evidence.

    Mechanism (spike-in-confirmed): a canonical junction fabricates a false
    NON-canonical junction only when the ``k`` bases that flip between exon and intron
    near-match the ``k`` bases at the drift distance (so ONT error tips the near-tie).
    A homopolymer is the MAXIMAL case (frac -> 1.0); this catches the PARTIAL-repeat
    non-HP drift the HP-guard misses.  A move to a genuine sequence transition (a real
    non-canonical splice site) has LOW microhomology (~0.25 random) and is untouched,
    preserving motif-blind discovery.

    Combination rule = MIN over the boundaries that ACTUALLY MOVED (audit A8): a move is
    drift-suspect only if EVERY shifted boundary sits in microhomology.  A genuine
    sequence TRANSITION on any moved boundary (low frac) SPARES the whole move — an
    unrelated tandem repeat on the OTHER boundary must not mask it (max() did, vetoing
    e.g. a both-boundary move whose donor abuts a (CAG)n microsatellite but whose
    acceptor is a real non-canonical transition).  A boundary that moved but runs off
    the genome edge (unassessable) contributes 0.0 → does not flag (favours discovery).
    Single-boundary moves are unchanged (min == that boundary's frac)."""
    n = len(seq)
    fracs: List[float] = []
    # Acceptor shift (intron|exon2): a k-bp slide between the two candidate acceptors is
    # enabled by a DOWNSTREAM tandem repeat seq[lo:hi] ~ seq[hi:hi+k] (the read's exon2
    # start k-mer repeats at the drift distance).  Direction-independent in lo/hi.
    if je != ne:
        lo, hi = (ne, je) if ne < je else (je, ne)
        k = hi - lo
        fracs.append(_frac_match(seq[lo:hi], seq[hi:hi + k]) if hi + k <= n else 0.0)
    # Donor shift (exon1|intron): enabled by an UPSTREAM tandem repeat
    # seq[lo-k:lo] ~ seq[lo:hi] (the read's exon1 end k-mer repeats upstream).
    if js != ns:
        lo, hi = (ns, js) if ns < js else (js, ns)
        k = hi - lo
        fracs.append(_frac_match(seq[lo - k:lo], seq[lo:hi]) if lo - k >= 0 else 0.0)
    return min(fracs) if fracs else 0.0


def _effective_veto_margin(hold_margin: float, eff_margin: float,
                           drift_near_tie_cap: float) -> float:
    """Effective move-veto margin after the read-evidence near-tie cap.

    ``eff_margin`` = ``hold_margin`` + drift-flagged additions (hp_drift + microhom_drift).
    The drift additions are decided from GENOMIC context ONLY (``_move_microhomology`` /
    ``_hp_run_across`` are read-blind), so on their own they can veto a move the READ
    strongly supports (a real cryptic the read distinguishes, delta_improve > 0).  When
    ``drift_near_tie_cap`` > 0, cap the DRIFT portion so the veto fires only within a
    near-tie band, while NEVER capping ``hold_margin`` (the read-agnostic blunt prior):

        veto_margin = max(hold_margin, min(eff_margin, drift_near_tie_cap))

    Consequence: a move with ``delta_improve >= drift_near_tie_cap`` is never drift-vetoed,
    bounding the read-blind discovery-loss.  HONEST SCOPE (see MICROHOM_AUDIT_SYNTHESIS.md):
    delta_improve, eff_margin and the cap share the SAME score axis, so the cap BOUNDS —
    it does not add a discriminating signal inside the ``(0, cap)`` near-tie band, where
    real cryptics and fabricated drift still overlap.  Cap disabled (<= 0.0) OR no drift
    margin added (eff_margin == hold_margin) → returns ``eff_margin`` unchanged
    (byte-identical to the pre-cap veto).
    """
    if drift_near_tie_cap > 0.0 and eff_margin > hold_margin:
        return max(hold_margin, min(eff_margin, drift_near_tie_cap))
    return eff_margin


def _semiglobal_ed(query: str, ref: str) -> int:
    """Edit distance aligning ALL of ``query`` to a PREFIX of ``ref`` (free ref suffix, HARD-
    anchored at ``ref[0]`` — no free query/ref prefix).  Indel-tolerant; lower = query matches
    ref better.  O(len(query)·len(ref)); only called on the rare would-be-veto path."""
    m, n = len(query), len(ref)
    if m == 0:
        return 0
    if n == 0:
        return m
    prev = list(range(n + 1))
    for i in range(1, m + 1):
        cur = [i] + [0] * n
        qi = query[i - 1]
        for j in range(1, n + 1):
            cost = 0 if qi == ref[j - 1] else 1
            cur[j] = min(prev[j - 1] + cost, prev[j] + 1, cur[j - 1] + 1)
        prev = cur
    return min(prev)


def _positional_signal(genome_seq: str, q: str, q_split: int, ne: int, new_je: int,
                       W: int = 28) -> Optional[int]:
    """Indel-robust positional-distinctiveness signal for an ACCEPTOR move ``ne -> new_je``.

    ``ed(rescue, incumbent exon2) - ed(rescue, moved exon2)`` where ``rescue = q[q_split:]`` is the
    read's exon2 bases.  ``> 0`` ⇒ the read's exon2 matches the MOVED acceptor better, i.e. genuine
    read evidence for the move — the discriminating bases the scorer's free-``k`` soft-clip escape
    HIDES from ``delta_improve``.  Hard-anchored (no free-prefix split) is exactly what removes that
    escape (panel: cap+ed(>0) → ~0.3% discovery loss at ~cap-alone fabrication; 98–99% balanced
    separation of real cryptics vs error-driven drift in the delta overlap band).

    ACCEPTOR-ONLY by design.  ``_score_junction`` is acceptor-centric (``intron_start`` is unused →
    the donor does not affect a candidate's score), so the refiner never discovers a donor-only move
    (both candidates tie → is_alt keeps the incumbent) — there is no donor-side discovery-loss to
    close.  For a both-boundary candidate the read's exon1 matches the aligner-placed (incumbent)
    donor, so a donor edit-distance term would go NEGATIVE and could drag a genuine acceptor cryptic's
    positive signal down, wrongly vetoing a real discovery.  So the discrimination lives entirely on
    the acceptor/exon2 side that actually drives placement.  (See DISCOVERY_LOSS_PANEL_RESULT.md.)

    Returns ``None`` when the acceptor did not move (exon2 discrimination undefined) or the rescue is
    empty — callers then leave the veto to the margin/cap alone (conservative)."""
    if new_je == ne:
        return None
    rescue = q[q_split:q_split + W]
    if not rescue:
        return None
    n = len(genome_seq)
    ref_inc = genome_seq[ne:min(n, ne + W + 6)]
    ref_mov = genome_seq[new_je:min(n, new_je + W + 6)]
    return _semiglobal_ed(rescue, ref_inc) - _semiglobal_ed(rescue, ref_mov)


def refine_read_junctions(
    read: pysam.AlignedSegment,
    all_junctions_idx: Dict[str, List[Tuple[int, int]]],
    annotated_set: Set[Junction],
    genome_seq: str,
    strand: str,
    hp_pen: float = 0.25,
    W: int = 15,
    max_slide: int = 10,
    search_radius: int = 5000,
    max_boundary_shift: int = 50,
    boundary_error_window: int = 10,
    max_junction_size: Optional[int] = None,
    max_candidates_per_nop: Optional[int] = None,
    profile: Optional[JunctionRefineProfile] = None,
    penalty_table: Optional[HpPenaltyTable] = None,
    motif_blind: bool = False,
    hold_margin: float = 0.0,
    hp_drift_margin: float = 0.0,
    hp_drift_min_run: int = 4,
    microhom_drift_margin: float = 0.0,
    microhom_threshold: float = 0.5,
    drift_near_tie_cap: float = 0.0,
    drift_positional_gate: float = 0.0,
) -> List[Tuple[int, int, int, int, int]]:
    """Find improved junctions for all N-ops in a read.

    Args:
        read:                 pysam AlignedSegment (not modified).
        all_junctions_idx:    Output of _build_junction_index.
        annotated_set:        Set of (chrom, js, je) for annotated junctions.
        genome_seq:           Full chromosome sequence.
        strand:               '+' or '-'.
        hp_pen:               Homopolymer indel penalty.
        W:                    Retained for API compatibility; unused by the
                              current HP-anchored semi-global implementation.
        max_slide:            Retained for API compatibility; unused by the
                              current HP-anchored semi-global implementation.
        search_radius:        Discovery radius for finding candidate junctions
                              (bp).  Large values ensure annotated junctions from
                              adjacent isoforms are included.
        max_boundary_shift:   Maximum allowed shift of either intron boundary
                              (bp).  Candidates where |new_ns - old_ns| or
                              |new_ne - old_ne| exceeds this threshold are
                              excluded.  Prevents pairing with junctions from
                              neighbouring genes that happen to score well due to
                              sequence coincidence in noisy Nanopore reads.
        boundary_error_window: Only refine N-ops that have at least one
                              mismatch (X) or indel (I/D) op within this many
                              reference bases of either junction boundary.
                              Reads with clean M-op alignments at the boundary
                              are already correctly placed and don't need
                              refinement.  Set to 0 to disable this filter and
                              score every N-op.
        max_junction_size:    Optional maximum candidate intron/junction length.
                              For yeast, 10000 keeps organism-plausible
                              junctions while removing long noisy N-op calls.
        max_candidates_per_nop:
                              Optional deterministic cap on candidates scored
                              per N-op after ranking current/annotated/nearby
                              candidates first.
        profile:              Optional aggregate profiler.

    Returns:
        List of (cigar_idx, old_start, old_end, new_start, new_end) for each
        N-op that should be updated.  Empty if no changes needed.
    """
    if not read.cigartuples or read.is_unmapped:
        return []

    chrom = standardize_chrom_name(read.reference_name)
    q = read.query_sequence
    if not q:
        return []

    replacements = []

    for cigar_idx, ns, ne, q_split in _iter_n_ops(read):
        if profile is not None:
            profile.inc('n_ops_examined')
        # Filter: only score junctions where there is alignment evidence of a
        # boundary problem — an X (mismatch) or I/D (indel) op within
        # boundary_error_window reference bases of either junction endpoint.
        # Clean M-op alignments at the boundary indicate the aligner was
        # confident; noisy boundaries are the cases that benefit from refinement.
        # Exception: non-canonical junctions (tier >= 4, e.g. GG/AT donor) are
        # ALWAYS scored regardless of boundary cleanliness — the aligner can
        # produce a locally-optimal but canonically-wrong split with no nearby
        # errors (e.g. 54= leading into a GG donor), and these are exactly the
        # cases that need correction.
        if boundary_error_window > 0:
            _t_boundary = time.perf_counter() if profile is not None else 0.0
            has_boundary_error = _has_boundary_error(
                read.cigartuples, ns, ne,
                read.reference_start, boundary_error_window,
            )
            _profile_time(profile, 'boundary_error_filter', _t_boundary)
            if not has_boundary_error:
                _t_tier = time.perf_counter() if profile is not None else 0.0
                current_filter_tier = _canonical_tier(ns, ne, genome_seq, strand)
                _profile_time(profile, 'canonical_tier_current_filter', _t_tier)
                if current_filter_tier < 4:
                    if profile is not None:
                        profile.inc('n_ops_skipped_boundary_clean')
                    continue
                if profile is not None:
                    profile.inc('n_ops_noncanonical_bypass_boundary_filter')
        # Use search_radius to discover candidates (finds annotated junctions from
        # adjacent isoforms), but constrain each endpoint to max_boundary_shift to
        # avoid pairing with junctions from entirely different genes.
        _t_candidates = time.perf_counter() if profile is not None else 0.0
        candidates = _candidates_near(
            all_junctions_idx, chrom, ns, ne,
            radius=search_radius,
            start_radius=max_boundary_shift,
            end_radius=max_boundary_shift,
            max_junction_size=max_junction_size,
        )
        _profile_time(profile, 'candidate_lookup', _t_candidates)
        if profile is not None:
            profile.observe_candidates(len(candidates))
        if not candidates:
            if profile is not None:
                profile.inc('n_ops_no_candidates')
            continue

        if max_candidates_per_nop and max_candidates_per_nop > 0:
            _t_cap = time.perf_counter() if profile is not None else 0.0
            capped_candidates = _rank_and_cap_candidates(
                candidates, chrom, ns, ne, annotated_set, max_candidates_per_nop
            )
            _profile_time(profile, 'candidate_rank_and_cap', _t_cap)
            if profile is not None:
                profile.observe_candidates(len(capped_candidates), after_cap=True)
                if len(capped_candidates) < len(candidates):
                    profile.inc('n_ops_candidate_capped')
                    profile.inc('candidates_dropped_by_cap', len(candidates) - len(capped_candidates))
            candidates = capped_candidates
        elif profile is not None:
            profile.observe_candidates(len(candidates), after_cap=True)

        if profile is not None:
            profile.inc('n_ops_scored')
            profile.inc('candidates_scored', len(candidates))

        # All candidates are scored; canonical/annotated status is used ONLY as
        # a tie-breaker for equal or near-equal sequence scores.
        # Policy: a non-canonical junction with ed=0 always beats canonical with
        # ed≥1.0; within the sub-integer HP noise floor (|ed_A - ed_B| < 1.0)
        # canonical annotated junctions are preferred.

        best_tuple = None   # best (score_bin, pri2, pri3, is_novel, abs_delta, js, je, delta)
        incumbent_score = None   # score_cmp of the current placement (for hold_margin)

        # Canonical tier of the current N-op determines tie-break priority ordering.
        # When the current junction is non-canonical (tier ≥ 4), a canonical
        # alternative should be preferred at equal edit-distance score (i.e., tier
        # comparison wins over is_alt).  When the current junction is acceptably
        # canonical (tier < 4), the read was placed there for good reason and the
        # current junction is preferred at equal score (is_alt wins over tier).
        _t_tier = time.perf_counter() if profile is not None else 0.0
        current_tier = _canonical_tier(ns, ne, genome_seq, strand)
        _profile_time(profile, 'canonical_tier_current_scoring', _t_tier)
        # Motif-blind (arm-B): decide placement on read evidence alone.  The current
        # junction's canonicity never triggers a canonical preference (so the
        # _CANONICAL_HP_PRIOR discount below is also disabled), and tier / is_novel
        # are dropped from the tie-break sort (below).  motif_blind=False is
        # byte-identical to the incumbent (arm-A).
        tier_beats_alt = (current_tier >= 4) and not motif_blind  # True → prefer canonical over current

        for js, je in candidates:
            if je <= js:
                if profile is not None:
                    profile.inc('candidates_invalid')
                continue

            _t_score = time.perf_counter() if profile is not None else 0.0
            score, delta = _score_junction(
                q, q_split, js, je, genome_seq,
                hp_pen=hp_pen, W=W, max_slide=max_slide,
                current_ns=ns,   # anchor: current N-op boundaries
                profile=profile,
                penalty_table=penalty_table,
            )
            _profile_time(profile, 'score_junction_call_wall', _t_score)

            # Tie-breakers (only matter when score is identical or within noise floor):
            is_alt   = 0 if (js == ns and je == ne) else 1  # current junction preferred
            _t_tiebreak = time.perf_counter() if profile is not None else 0.0
            tier     = _canonical_tier(js, je, genome_seq, strand)
            is_novel = 0 if (chrom, js, je) in annotated_set else 1
            _profile_time(profile, 'candidate_tiebreak_metadata', _t_tiebreak)

            # When the current junction is non-canonical, apply _CANONICAL_HP_PRIOR
            # (0.5 edit-distance units) as a discount to canonical-tier junctions so
            # that canonical alternatives win within the HP noise floor regardless of
            # which penalty table is in use.  Non-canonical candidates (tier ≥ 4) get
            # no discount.  When the current junction is canonical, compare raw scores.
            if tier_beats_alt:
                canonical_discount = _CANONICAL_HP_PRIOR if tier < 4 else 0.0
                score_cmp = score - canonical_discount
            else:
                score_cmp = score
            if is_alt == 0:              # this candidate IS the read's current placement
                incumbent_score = score_cmp

            # Scoring priority (lower = better):
            #   1. score_cmp — binned when tier_beats_alt, raw otherwise
            #   2. tier / is_alt (order depends on current_tier — see above)
            #   3. is_alt / tier (the other one)
            #   4. is_novel  — annotated preferred over novel
            #   5. abs_delta — prefer minimal rescue split (final tiebreaker only).
            #      INERT: `_score_junction` returns delta=0 for every candidate
            #      (it never slides — `max_slide` is API-compat only), so this
            #      slot is a constant and ties fall through to (js, je), i.e. to
            #      the lower genomic coordinate. Closing that gap means DEFINING
            #      a new tie-break signal, not restoring a lost one (ISSUE-005).
            # Motif-blind drops the canonical-tier and annotation priors from the
            # tie-break (they collapse to constants), leaving score → is_alt → shift.
            tier_key = 0 if motif_blind else tier
            novel_key = 0 if motif_blind else is_novel
            if tier_beats_alt:
                # Current junction is non-canonical: prefer canonical alternatives
                candidate_tuple = (score_cmp, tier_key, is_alt, novel_key, abs(delta), js, je, delta)
            else:
                # Current junction is acceptably canonical: prefer it at equal score
                candidate_tuple = (score_cmp, is_alt, tier_key, novel_key, abs(delta), js, je, delta)
            if best_tuple is None or candidate_tuple < best_tuple:
                best_tuple = candidate_tuple

        if best_tuple is None:
            continue

        # best_tuple = (score, pri2, pri3, is_novel, abs_delta, js, je, delta)
        best_score_cmp = best_tuple[0]
        _, _, _, _, _, new_js, new_je, _ = best_tuple

        moves = (new_js != ns or new_je != ne)
        # Move gate.  Two priors against a marginally-better-scoring displacement:
        #   * hold_margin      — a BLUNT prior: any move must beat the incumbent by it.
        #   * hp_drift_margin   — a TARGETED prior: only a move that slides a boundary
        #                         INTO a homopolymer run (the ubiquitous-undercall
        #                         drift that fabricates false non-canonical junctions)
        #                         must clear the extra margin; a move to a genuine
        #                         sequence transition (a real non-canonical acceptor)
        #                         is untouched, preserving motif-blind discovery.
        # Both default to 0.0 → byte-identical incumbent behaviour.
        eff_margin = hold_margin
        if moves and hp_drift_margin > 0.0:
            into_hp = (_hp_run_across(genome_seq, new_js, hp_drift_min_run) > 0 or
                       _hp_run_across(genome_seq, new_je, hp_drift_min_run) > 0)
            if into_hp:
                eff_margin += hp_drift_margin
                if profile is not None:
                    profile.inc('hp_drift_flagged')
        #   * microhom_drift_margin — the GENERAL analog of hp_drift_margin: a move
        #     whose boundary shift sits in a local MICROHOMOLOGY context (a near-tandem
        #     repeat at the drift distance, microhomology fraction >= microhom_threshold)
        #     is the non-homopolymer drift that fabricates false non-canonical junctions
        #     (spike-in-confirmed, HP-guard-blind). A move to a genuine transition (low
        #     microhomology, a real non-canonical site) is untouched. Default 0.0 → off.
        if moves and microhom_drift_margin > 0.0:
            if _move_microhomology(genome_seq, ns, ne, new_js, new_je) >= microhom_threshold:
                eff_margin += microhom_drift_margin
                if profile is not None:
                    profile.inc('microhom_drift_flagged')
        #   * drift_near_tie_cap — a READ-EVIDENCE ceiling on the read-BLIND drift
        #     margins (hp_drift + microhom_drift are decided from GENOMIC context only,
        #     so on their own they can veto a move the READ strongly supports). When
        #     > 0.0, cap the drift-added portion of eff_margin so the drift veto fires
        #     only within a near-tie band: veto_margin = max(hold_margin,
        #     min(eff_margin, drift_near_tie_cap)). hold_margin (read-agnostic blunt
        #     prior) is NEVER capped. NOTE (honest framing — see MICROHOM_AUDIT_SYNTHESIS):
        #     delta_improve, eff_margin and the cap all live on the SAME scalar (score)
        #     axis, so the cap BOUNDS the read-blind discovery-loss (a move with
        #     delta_improve >= cap is never drift-vetoed) but does NOT add a new
        #     discriminating signal inside the (0, cap) band. Its value is STRUCTURAL:
        #     it decouples hold_margin from the drift margins and makes the discovery-loss
        #     ceiling explicit + tunable. Default 0.0 → cap disabled → byte-identical.
        #   * drift_positional_gate — the read-evidence signal that CLOSES the read-blind
        #     fault (the cap only BOUNDS it — same score axis).  When a drift-context move
        #     would be vetoed, SPARE it if the read carries indel-robust POSITIONAL evidence
        #     for the moved acceptor: `_positional_signal` (hard-anchored edit distance,
        #     removing the scorer's free-k soft-clip escape) >= the gate.  This separates a
        #     real cryptic (read matches the moved exon2) from an error-driven drift (read
        #     matches the incumbent) INSIDE the delta near-tie band the cap cannot.  Default
        #     0.0 → gate off → byte-identical.  (Acceptor moves only; donor/both-boundary
        #     moves fall through to the margin/cap decision — conservative.)
        if moves and eff_margin > 0.0 and incumbent_score is not None:
            veto_margin = _effective_veto_margin(hold_margin, eff_margin, drift_near_tie_cap)
            if profile is not None and veto_margin < eff_margin:
                profile.inc('near_tie_cap_applied')
            if best_score_cmp > incumbent_score - veto_margin:
                spared = False
                if drift_positional_gate > 0.0:
                    psig = _positional_signal(genome_seq, q, q_split, ne, new_je)
                    if psig is not None and psig >= drift_positional_gate:
                        spared = True
                        if profile is not None:
                            profile.inc('positional_gate_spared')
                if not spared:
                    moves = False
                    if profile is not None:
                        profile.inc('move_margin_vetoes')

        # --- Annotated-canonical evidence gate (the R1 class) -----------------
        # The policy stated at the top of this loop — "within the sub-integer HP
        # noise floor (|ed_A - ed_B| < 1.0) canonical annotated junctions are
        # preferred" — was only ever implemented for the tier_beats_alt branch
        # (where _CANONICAL_HP_PRIOR discounts canonical candidates).  In the
        # other branch, where the incumbent IS canonical, candidates are ranked
        # on the RAW score, so a 0.03 edit-distance win could take an annotated
        # GT-AG junction onto a novel non-canonical one.  Measured on the Sumner
        # human panel: three such moves at margins 0.031 / 0.434 / 0.463, all far
        # inside the noise floor, each turning an annotated GT-AG into GT-GT /
        # GT-GA / CT-TC.
        #
        # So: when the incumbent is BOTH annotated and canonical, a candidate
        # that is not both must beat it by a full edit-distance unit.  Moves to
        # another annotated canonical junction (isoform swaps) and moves whose
        # incumbent is novel or non-canonical (the corrections 2H exists for) are
        # untouched.  Disabled under motif_blind, which decides on read evidence
        # alone by construction.
        if (
            moves
            and _ANNOTATED_CANONICAL_HOLD > 0.0
            and not motif_blind
            and incumbent_score is not None
            and current_tier < 4
            and (chrom, ns, ne) in annotated_set
        ):
            _win_tier = _canonical_tier(new_js, new_je, genome_seq, strand)
            _win_annot = (chrom, new_js, new_je) in annotated_set
            if not (_win_annot and _win_tier < 4):
                if best_score_cmp > incumbent_score - _ANNOTATED_CANONICAL_HOLD:
                    moves = False
                    if profile is not None:
                        profile.inc('annotated_canonical_holds')

        # Only emit a replacement if the junction actually changes.
        if moves:
            replacements.append((cigar_idx, ns, ne, new_js, new_je))
            if profile is not None:
                profile.inc('replacements_emitted')

    return replacements


# ---------------------------------------------------------------------------
# CIGAR surgery: apply junction replacement
# ---------------------------------------------------------------------------

def _apply_junction_replacement(
    read: pysam.AlignedSegment,
    cigar_idx: int,
    old_ns: int,
    old_ne: int,
    new_ns: int,
    new_ne: int,
    genome_seq: str,
    strand: str,
    hp_pen: float,
    W: int,
) -> bool:
    """Replace one N-op in-place and re-align flanking exon CIGAR ops.

    The flanking exon ops (query bases that overlap the boundary difference)
    are trimmed and re-emitted as M ops against the new junction.  The
    reference_start is updated if the leftmost exon changes.

    Args:
        read:       Modified in-place.
        cigar_idx:  Index of the N-op in read.cigartuples.
        old_ns/ne:  Current intron coordinates.
        new_ns/ne:  Replacement intron coordinates.
        genome_seq: Full chromosome sequence.
        strand:     '+' or '-'.
        hp_pen:     For local realignment (not used directly here).
        W:          Window for CIGAR reconstruction.

    Returns:
        True if CIGAR was modified.
    """
    from ..align.local_aligner import align_clip_to_exon, cigar_ops_to_str, cigar_str_to_ops

    cigar = list(read.cigartuples)
    q = read.query_sequence
    if not cigar or not q:
        return False

    # Delta in intron boundaries
    delta_start = new_ns - old_ns   # positive = intron grew on left (ate exon2 bases)
    delta_end   = new_ne - old_ne   # positive = intron shrunk on right (exon1 got more)

    new_cigar = list(cigar)
    new_ref_start = read.reference_start

    # --- Fast path: pure k-bp slide on splice-ambiguous bases ---
    #
    # When delta_start == delta_end == k (pure slide, no length change to the
    # intron) AND the k genome bases that flip role between intron-edge and
    # exon-edge are identical at both placements, the slide is a trivial CIGAR
    # transformation: extend the boundary =/M op on one side of N by k and
    # shrink the boundary =/M op on the other side by k.  The read base whose
    # role flips has the same identity at both genomic positions, so an =-op
    # at the old placement remains an =-op at the new placement.
    #
    # This avoids the boundary D/I insertions that the general path emits, which
    # are then mangled by the downstream indel corrector into degenerate
    # local-realignment CIGARs (e.g. 14=1D8=1D366N1I50= → 22D1M20I1M366N1I50=).
    #
    # The transformation is strand-agnostic: CIGAR ops are always in genomic
    # order, so we only care about which adjacent op is upstream (lower genomic
    # coord) and which is downstream (higher).  Strand only affects which end
    # is the donor vs acceptor, which the fast path doesn't need to know.
    if (
        delta_start == delta_end
        and delta_start != 0
        and abs(delta_start) <= 50  # same _MAX_BOUNDARY_SHIFT guard as below
        and 0 < cigar_idx < len(new_cigar) - 1
    ):
        k = delta_start  # signed slide magnitude (positive = N slid right)
        absk = abs(k)

        # Adjacent ops: must be =/M on both sides for the slide to remain valid
        # as a pure match-extension transformation.
        up_op, up_len = new_cigar[cigar_idx - 1]
        dn_op, dn_len = new_cigar[cigar_idx + 1]

        if up_op in (_EQ, _M) and dn_op in (_EQ, _M):
            # Identify the read base(s) whose role flips and the two genomic
            # positions they would align to.
            #
            # k > 0 (intron slides right by k): genome positions [old_ns,
            #   old_ns + k) flip from intron to upstream-exon; positions
            #   [old_ne, old_ne + k) flip from downstream-exon to intron.
            #   The read base previously aligned to genome[old_ne + i] is now
            #   aligned to genome[old_ns + i].  For an =-op to remain valid,
            #   genome[old_ns + i] == genome[old_ne + i] for i in [0, k).
            #
            # k < 0 (intron slides left by |k|): genome positions [old_ns - |k|,
            #   old_ns) flip from upstream-exon to intron; positions
            #   [old_ne - |k|, old_ne) flip from intron to downstream-exon.
            #   The read base previously aligned to genome[old_ns - 1 - i] is
            #   now aligned to genome[old_ne - 1 - i].  Need genome[old_ns - 1
            #   - i] == genome[old_ne - 1 - i] for i in [0, |k|).
            gs = len(genome_seq)
            ok = True
            if k > 0:
                if old_ne + k > gs or old_ns < 0:
                    ok = False
                else:
                    for i in range(k):
                        if genome_seq[old_ns + i].upper() != genome_seq[old_ne + i].upper():
                            ok = False
                            break
                # Shrinking side: downstream op must have length >= k
                if ok and dn_len < k:
                    ok = False
            else:  # k < 0
                if old_ne + k < 0 or old_ns > gs:
                    ok = False
                else:
                    for i in range(absk):
                        if genome_seq[old_ns - 1 - i].upper() != genome_seq[old_ne - 1 - i].upper():
                            ok = False
                            break
                # Shrinking side: upstream op must have length >= |k|
                if ok and up_len < absk:
                    ok = False

            if ok:
                # k > 0: upstream =/M gains k; downstream =/M loses k.
                # k < 0: upstream =/M loses |k|; downstream =/M gains |k|.
                if k > 0:
                    new_up_len = up_len + k
                    new_dn_len = dn_len - k
                else:
                    new_up_len = up_len + k  # k is negative → subtracts
                    new_dn_len = dn_len - k  # k is negative → adds

                # N length is unchanged (pure slide preserves intron length).
                n_len = old_ne - old_ns
                new_cigar[cigar_idx - 1] = (up_op, new_up_len)
                new_cigar[cigar_idx]     = (_N, n_len)
                new_cigar[cigar_idx + 1] = (dn_op, new_dn_len)

                # Span checks: ref span gains k from upstream and loses k from
                # downstream (or vice versa) — net zero.  Same for query span.
                read.cigartuples = new_cigar
                # reference_start unchanged (we never touched leading ops)
                return True
        # Fall through to general path if fast-path preconditions not met

    # --- Fix intron start boundary ---
    # If delta_start > 0: intron_start moved right → exon2 gained |delta_start| ref bases
    #                      (need to add M ops before N from exon2 query bases absorbed in old N)
    # If delta_start < 0: intron_start moved left → exon2 lost |delta_start| ref bases
    #                      (trim those bases from the last exon2 op before N)
    #
    # --- Fix intron end boundary ---
    # If delta_end > 0: intron_end moved right → exon1 lost |delta_end| ref bases
    # If delta_end < 0: intron_end moved left → exon1 gained |delta_end| ref bases

    # Replace just the N length; flanking ops are handled via re-query alignment.
    # Simple approach: update N length and adjust adjacent M/D/X ops by the deltas.
    # For the exon2 side (left of N, index cigar_idx-1):
    #   shrink/grow the last M-consuming op
    # For the exon1 side (right of N, index cigar_idx+1):
    #   shrink/grow the first M-consuming op

    new_n_len = new_ne - new_ns
    if new_n_len <= 0:
        return False

    # Guard: refuse replacements with unreasonably large boundary shifts.
    # Legitimate junction corrections are at most a few bp off; large deltas
    # indicate a mis-matched junction pair (e.g., an annotated junction from a
    # completely different gene that happens to be within search_radius).
    _MAX_BOUNDARY_SHIFT = 50  # bp
    if abs(delta_start) > _MAX_BOUNDARY_SHIFT or abs(delta_end) > _MAX_BOUNDARY_SHIFT:
        logger.debug(
            "_apply_junction_replacement: boundary shift too large "
            "(delta_start=%d, delta_end=%d) for read %s — skipping",
            delta_start, delta_end, read.query_name,
        )
        return False

    new_cigar[cigar_idx] = (_N, new_n_len)

    # --- Adjust exon2 flank ---
    # The challenge: M ops consume both ref AND query, so we can't simply shrink/grow
    # an M without disturbing the query span.  Instead we insert boundary ops:
    #
    #   delta_start > 0  (N start moved right; intron gave d ref bases to exon2)
    #     → those d ref positions had NO query bases (they were in the N)
    #     → encode as D(d) at the right edge of exon2: M(m)D(d)N(L')
    #     → ref: +d from D ✓;  query: unchanged ✓
    #
    #   delta_start < 0  (N start moved left; exon2 lost d ref bases into intron)
    #     → those d query bases that were in exon2 M are now "inside" the intron
    #     → encode as I(d) at the right edge of exon2 (before N): M(m-d)I(d)N(L')
    #     → ref: -d from shrunk M ✓;  query: unchanged (M loses d, I gains d) ✓
    # Track N-op index explicitly through inserts (do NOT search — reads may have
    # multiple N-ops, and a search could match the wrong one).
    n_idx = cigar_idx  # starts at original position; updated as inserts shift it

    if delta_start != 0:
        d = abs(delta_start)
        # Find the last ref-consuming op before n_idx
        ins_k = -1
        for k in range(n_idx - 1, -1, -1):
            if new_cigar[k][0] in _REF_CONSUMING:
                ins_k = k
                break
        if ins_k < 0:
            return False  # no ref-consuming op found before N

        op_k, len_k = new_cigar[ins_k]

        if delta_start > 0:
            # Exon2 gained d ref bases from the intron.  Encode as D(d) before N.
            new_cigar.insert(n_idx, (_D, d))
            n_idx += 1  # N shifted right by 1 due to insert
        else:
            # delta_start < 0: exon2 lost d ref bases into intron.
            # Walk backward from n_idx-1, consuming d ref bases (may span multiple ops).
            remaining_ref = d
            absorbed_q = 0
            ops_start = n_idx  # exclusive start: we remove ops in [ops_start, n_idx)
            leftover_op2: Optional[Tuple[int, int]] = None

            for k in range(n_idx - 1, -1, -1):
                op_k2, len_k2 = new_cigar[k]
                if op_k2 in _REF_CONSUMING:
                    if remaining_ref <= 0:
                        break
                    take_ref = min(len_k2, remaining_ref)
                    take_q   = take_ref if op_k2 in _QUERY_CONSUMING else 0
                    absorbed_q += take_q
                    remaining_ref -= take_ref
                    if take_ref < len_k2:
                        leftover_op2 = (op_k2, len_k2 - take_ref)
                        ops_start = k
                        break
                    else:
                        ops_start = k
                elif op_k2 in _QUERY_CONSUMING:
                    absorbed_q += len_k2
                    ops_start = k

            if remaining_ref > 0:
                return False

            # Remove consumed ops
            del new_cigar[ops_start: n_idx]
            n_idx = ops_start  # N shifted left
            if leftover_op2 is not None:
                new_cigar.insert(n_idx, leftover_op2)
                n_idx += 1
            # Append I(absorbed_q) right before N
            if absorbed_q > 0:
                new_cigar.insert(n_idx, (_I, absorbed_q))
                n_idx += 1

    # --- Adjust exon1 flank ---
    #   delta_end > 0  (N end moved right; exon1 lost d ref bases into intron)
    #     → those d query bases from exon1 M can't just vanish
    #     → encode as I(d) at the left edge of exon1: N(L')I(d)M(m-d)
    #     → ref: M loses d ✓;  query: unchanged (M loses d, I gains d) ✓
    #
    #   delta_end < 0  (N end moved left; exon1 gained d ref bases from intron)
    #     → those d positions had NO query bases (they were in the N)
    #     → encode as D(d) at the left edge of exon1: N(L')D(d)M(m)
    #     → ref: +d from D ✓;  query: unchanged ✓
    if delta_end != 0:
        d = abs(delta_end)

        if delta_end > 0:
            # Exon1 lost d ref bases into the intron.  Those bases were previously
            # aligned (M/=/X ops) and carried query bases with them.  We need to:
            #   1. Remove d ref-consuming bases from the start of exon1 (may span
            #      multiple ops, along with any I ops interleaved between them).
            #   2. Prepend I(absorbed_query) to preserve the query span.
            # Walk forward from n_idx+1, consuming ops until d ref bases absorbed.
            remaining_ref = d
            absorbed_q = 0
            ops_to_remove_end = n_idx + 1  # exclusive end index of consumed ops
            leftover_op: Optional[Tuple[int, int]] = None  # partial op remainder

            for k in range(n_idx + 1, len(new_cigar)):
                op_k, len_k = new_cigar[k]
                if op_k in _REF_CONSUMING:
                    if remaining_ref <= 0:
                        break
                    take_ref = min(len_k, remaining_ref)
                    take_q   = take_ref if op_k in _QUERY_CONSUMING else 0
                    absorbed_q += take_q
                    remaining_ref -= take_ref
                    if take_ref < len_k:
                        # Partial consumption — save the remainder
                        leftover_op = (op_k, len_k - take_ref)
                        ops_to_remove_end = k + 1
                        break
                    else:
                        ops_to_remove_end = k + 1
                elif op_k in _QUERY_CONSUMING:
                    # I/S op interleaved with ref ops: absorb its query bases too
                    absorbed_q += len_k
                    ops_to_remove_end = k + 1

            if remaining_ref > 0:
                # Could not absorb all d ref bases (exon1 too short)
                return False

            # Remove consumed ops, optionally re-insert leftover
            del new_cigar[n_idx + 1: ops_to_remove_end]
            if leftover_op is not None:
                new_cigar.insert(n_idx + 1, leftover_op)
            # Prepend I(absorbed_q) right after N to preserve query span
            if absorbed_q > 0:
                new_cigar.insert(n_idx + 1, (_I, absorbed_q))

        else:
            # Exon1 gained |d| ref bases from the intron.  Those bases had NO
            # query counterpart (they were in the N-op).  Encode as D(d).
            new_cigar.insert(n_idx + 1, (_D, d))

    # Validate: total ref span must be preserved (sum ref ops + N = constant)
    old_ref_span = sum(l for op, l in cigar     if op in _REF_CONSUMING_POS)
    new_ref_span = sum(l for op, l in new_cigar if op in _REF_CONSUMING_POS)
    if old_ref_span != new_ref_span:
        logger.debug(
            "refine_junction: ref span mismatch (%d → %d) for read %s; skipping",
            old_ref_span, new_ref_span, read.query_name,
        )
        return False

    # Validate: total query span unchanged
    old_q_span = sum(l for op, l in cigar     if op in _QUERY_CONSUMING)
    new_q_span = sum(l for op, l in new_cigar if op in _QUERY_CONSUMING)
    if old_q_span != new_q_span:
        logger.debug(
            "refine_junction: query span mismatch (%d → %d) for read %s; skipping",
            old_q_span, new_q_span, read.query_name,
        )
        return False

    # INVARIANT: refuse a BOTH-BOUNDARY move that increases the read's indel burden.
    #
    # The general path preserves the query span by re-labelling boundaries with
    # COMPENSATING I/D ops — it never re-aligns the flank.  When BOTH the donor and the
    # acceptor shift (delta_start != 0 AND delta_end != 0) and the move is not a clean
    # microhomology slide (those return early via the fast path), it can only realize
    # the move by adding compensating indel on BOTH flanks: a pure k-bp slide →
    # I(k) … N … D(k), an asymmetric both-shift → D(a) … N … D(b).  The exon SEQUENCE
    # stays where the aligner put it while only the N-op COORDINATE moves — fabricating
    # a false junction position (and the downstream indel corrector mangles it further,
    # not better — see the fast-path note above).  On real ONT DRS this was ~85–95% of
    # "moved" reads at the SMA leads (dev/REPLACER_COMPENSATING_INDEL_BUG.md), a phantom
    # 6–48 bp "drift".  Refinement corrects ONE splice site at a time; a simultaneous
    # donor+acceptor relocation via compensating indels is the fabrication signature.
    #
    # Single-boundary corrections (donor-only or acceptor-only) are NOT touched — they
    # move one splice site and the indel they add represents a real intron-length change
    # at that site (e.g. 10M100N10M → 10M3D97N10M).  A move that REDUCES indel burden
    # (cleaning a boundary error) is always applied.  Refused reads keep their incumbent
    # (raw) placement — the conservative, correct outcome.
    if delta_start != 0 and delta_end != 0:
        old_indel = sum(l for op, l in cigar     if op in (_I, _D))
        new_indel = sum(l for op, l in new_cigar if op in (_I, _D))
        if new_indel > old_indel:
            logger.debug(
                "refine_junction: both-boundary move adds compensating indel "
                "(%d → %d) for read %s — unsupported relocation, refusing",
                old_indel, new_indel, read.query_name,
            )
            return False

    read.cigartuples = new_cigar
    if new_ref_start != read.reference_start:
        read.reference_start = new_ref_start

    return True


# ---------------------------------------------------------------------------
# Internal helpers for sequential and parallel BAM processing
# ---------------------------------------------------------------------------

def _apply_replacements_to_read(
    read: pysam.AlignedSegment,
    replacements: list,
    genome_seq: str,
    strand: str,
    hp_pen: float,
    W: int,
) -> Tuple[pysam.AlignedSegment, bool]:
    """Apply junction replacements to *read* and return (modified_read, any_applied).

    Returns the original *read* unchanged if no replacements apply or if the
    copy fails.
    """
    try:
        modified_read = read.__copy__()
    except Exception:
        return read, False

    any_applied = False
    for cigar_idx, old_ns, old_ne, new_ns, new_ne in sorted(
        replacements, key=lambda r: -r[0]
    ):
        try:
            applied = _apply_junction_replacement(
                modified_read, cigar_idx, old_ns, old_ne, new_ns, new_ne,
                genome_seq, strand, hp_pen, W,
            )
            any_applied = any_applied or applied
        except Exception as exc:
            logger.debug(
                "_apply_junction_replacement failed for %s: %s",
                read.query_name, exc,
            )

    if any_applied:
        # Strip MD and cs tags from modified reads: the CIGAR has been
        # changed (boundary D/I ops inserted) so the MD string is now
        # invalid.  Without MD, downstream tools (pysam indel corrector)
        # skip MD-based processing, which is correct.  Also strip cs
        # (cigar string in cs notation) for the same reason.
        try:
            modified_read.set_tags([
                t for t in modified_read.tags if t[0] not in ('MD', 'cs')
            ])
        except Exception:
            pass

    return modified_read, any_applied


def _run_sequential(
    input_bam: str,
    output_bam: str,
    genome: Dict[str, str],
    junctions_idx: Dict,
    annotated_set: Set,
    stats: Dict[str, int],
    hp_pen: float,
    W: int,
    max_slide: int,
    search_radius: int,
    max_boundary_shift: int,
    boundary_error_window: int,
    max_junction_size: Optional[int],
    max_candidates_per_nop: Optional[int],
    penalty_table: Optional[HpPenaltyTable],
    penalty_table_set: Optional[PenaltyTableSet] = None,
    motif_blind: bool = False,
    hold_margin: float = 0.0,
    hp_drift_margin: float = 0.0,
    hp_drift_min_run: int = 4,
    microhom_drift_margin: float = 0.0,
    microhom_threshold: float = 0.5,
    drift_near_tie_cap: float = 0.0,
    drift_positional_gate: float = 0.0,
    profile: Optional[JunctionRefineProfile] = None,
) -> None:
    """Single-threaded sequential junction refinement (original code path)."""
    sample_rate = profile.sample_rate if profile is not None else 1
    with pysam.AlignmentFile(input_bam, 'rb') as bam_in, \
         pysam.AlignmentFile(output_bam, 'wb', header=bam_in.header) as bam_out:

        for read in bam_in:
            stats['total'] += 1
            if read.is_unmapped or not read.cigartuples:
                bam_out.write(read)
                stats['unchanged'] += 1
                continue

            if not any(op == _N for op, _ in read.cigartuples):
                bam_out.write(read)
                stats['unchanged'] += 1
                continue

            stats['n_op_reads'] += 1
            strand = '-' if read.is_reverse else '+'
            chrom = standardize_chrom_name(read.reference_name)
            genome_seq = genome.get(chrom, '')
            if not genome_seq:
                bam_out.write(read)
                stats['unchanged'] += 1
                continue

            eff_table = (penalty_table_set.for_read(read)
                         if penalty_table_set is not None else penalty_table)
            try:
                read_profile = (
                    profile
                    if profile is not None and (stats['n_op_reads'] % sample_rate == 0)
                    else None
                )
                replacements = refine_read_junctions(
                    read, junctions_idx, annotated_set, genome_seq, strand,
                    hp_pen=hp_pen, W=W, max_slide=max_slide,
                    search_radius=search_radius,
                    max_boundary_shift=max_boundary_shift,
                    boundary_error_window=boundary_error_window,
                    max_junction_size=max_junction_size,
                    max_candidates_per_nop=max_candidates_per_nop,
                    profile=read_profile,
                    penalty_table=eff_table,
                    motif_blind=motif_blind,
                    hold_margin=hold_margin,
                    hp_drift_margin=hp_drift_margin,
                    hp_drift_min_run=hp_drift_min_run,
                    microhom_drift_margin=microhom_drift_margin,
                    microhom_threshold=microhom_threshold,
                    drift_near_tie_cap=drift_near_tie_cap,
                    drift_positional_gate=drift_positional_gate,
                )
            except Exception as exc:
                logger.debug("refine_read_junctions failed for %s: %s", read.query_name, exc)
                bam_out.write(read)
                stats['errors'] += 1
                continue

            if not replacements:
                bam_out.write(read)
                stats['unchanged'] += 1
                continue

            modified_read, any_applied = _apply_replacements_to_read(
                read, replacements, genome_seq, strand, hp_pen, W,
            )
            bam_out.write(modified_read)
            if any_applied:
                stats['refined'] += 1
            else:
                stats['unchanged'] += 1


def _run_parallel(
    input_bam: str,
    output_bam: str,
    genome: Dict[str, str],
    junctions_idx: Dict,
    annotated_set: Set,
    stats: Dict[str, int],
    hp_pen: float,
    W: int,
    max_slide: int,
    search_radius: int,
    max_boundary_shift: int,
    boundary_error_window: int,
    max_junction_size: Optional[int],
    max_candidates_per_nop: Optional[int],
    penalty_table: Optional[HpPenaltyTable],
    n_workers: int,
    batch_size: int,
    penalty_table_set: Optional[PenaltyTableSet] = None,
    motif_blind: bool = False,
    hold_margin: float = 0.0,
    hp_drift_margin: float = 0.0,
    hp_drift_min_run: int = 4,
    microhom_drift_margin: float = 0.0,
    microhom_threshold: float = 0.5,
    drift_near_tie_cap: float = 0.0,
    drift_positional_gate: float = 0.0,
    profile: Optional[JunctionRefineProfile] = None,
) -> None:
    """Parallel junction refinement using multiprocessing.Pool (Linux fork).

    Phase 1: Read all reads; write pass-throughs immediately; collect N-op
             reads as SAM strings.
    Phase 2: Process N-op batches in parallel workers (fork-inherited state).
    Phase 3: Apply replacements in main process and write to output BAM.
    """
    import multiprocessing as mp

    # Phase 1: separate pass-through reads from N-op reads, write pass-throughs
    _t_scan = time.perf_counter() if profile is not None else 0.0
    n_op_sams: List[str] = []
    with pysam.AlignmentFile(input_bam, 'rb') as bam_in:
        header_dict = bam_in.header.to_dict()
        for read in bam_in:
            stats['total'] += 1
            if (read.is_unmapped or not read.cigartuples
                    or not any(op == _N for op, _ in read.cigartuples)):
                stats['unchanged'] += 1
                continue
            stats['n_op_reads'] += 1
            n_op_sams.append(read.to_string())
    _profile_time(profile, 'parallel_bam_scan_collect_nop_reads', _t_scan)

    if not n_op_sams:
        # No N-op reads: just copy the BAM
        with pysam.AlignmentFile(input_bam, 'rb') as bam_in, \
             pysam.AlignmentFile(output_bam, 'wb', header=bam_in.header) as bam_out:
            for read in bam_in:
                bam_out.write(read)
        return

    # Populate worker state before Pool() creation so workers inherit it via fork
    _WORKER_POOL_STATE.clear()
    _WORKER_POOL_STATE['header'] = pysam.AlignmentHeader.from_dict(header_dict)
    _WORKER_POOL_STATE['junctions_idx'] = junctions_idx
    _WORKER_POOL_STATE['annotated_set'] = annotated_set
    _WORKER_POOL_STATE['genome'] = genome
    _WORKER_POOL_STATE['kwargs'] = {
        'hp_pen': hp_pen, 'W': W, 'max_slide': max_slide,
        'search_radius': search_radius,
        'max_boundary_shift': max_boundary_shift,
        'boundary_error_window': boundary_error_window,
        'max_junction_size': max_junction_size,
        'max_candidates_per_nop': max_candidates_per_nop,
        'penalty_table': penalty_table,
        'motif_blind': motif_blind,
        'hold_margin': hold_margin,
        'hp_drift_margin': hp_drift_margin,
        'hp_drift_min_run': hp_drift_min_run,
        'microhom_drift_margin': microhom_drift_margin,
        'microhom_threshold': microhom_threshold,
        'drift_near_tie_cap': drift_near_tie_cap,
        'drift_positional_gate': drift_positional_gate,
    }
    _WORKER_POOL_STATE['penalty_table_set'] = penalty_table_set
    _WORKER_POOL_STATE['profile_enabled'] = profile is not None
    _WORKER_POOL_STATE['profile_sample_rate'] = profile.sample_rate if profile is not None else 1

    # Trigger numba JIT compilation before forking so workers inherit compiled code
    if _NUMBA_AVAILABLE:
        _warmup_numba_dp()

    bam_hdr = pysam.AlignmentHeader.from_dict(header_dict)
    batches = [n_op_sams[i:i + batch_size] for i in range(0, len(n_op_sams), batch_size)]
    all_results: List[Tuple[str, List]] = []

    # Phase 2: parallel scoring
    _t_workers = time.perf_counter() if profile is not None else 0.0
    with mp.Pool(n_workers) as pool:
        for batch_results in pool.imap_unordered(_refine_read_batch, batches):
            if isinstance(batch_results, dict):
                all_results.extend(batch_results.get('results', []))
                if profile is not None:
                    profile.merge(batch_results.get('profile'))
            else:
                all_results.extend(batch_results)
    _profile_time(profile, 'parallel_worker_scoring', _t_workers)

    _WORKER_POOL_STATE.clear()

    # Phase 3: write all output (pass-throughs first, then N-op results)
    _t_write = time.perf_counter() if profile is not None else 0.0
    with pysam.AlignmentFile(input_bam, 'rb') as bam_in, \
         pysam.AlignmentFile(output_bam, 'wb', header=bam_in.header) as bam_out:

        # Write pass-through reads from input
        for read in bam_in:
            if (read.is_unmapped or not read.cigartuples
                    or not any(op == _N for op, _ in read.cigartuples)):
                bam_out.write(read)

        # Write N-op reads with replacements applied
        for sam_str, replacements in all_results:
            read = pysam.AlignedSegment.fromstring(sam_str, bam_hdr)
            if not replacements:
                bam_out.write(read)
                stats['unchanged'] += 1
                continue
            chrom = standardize_chrom_name(read.reference_name)
            genome_seq = genome.get(chrom, '')
            strand = '-' if read.is_reverse else '+'
            modified_read, any_applied = _apply_replacements_to_read(
                read, replacements, genome_seq, strand, hp_pen, W,
            )
            bam_out.write(modified_read)
            if any_applied:
                stats['refined'] += 1
            else:
                stats['unchanged'] += 1
    _profile_time(profile, 'parallel_output_write_apply_replacements', _t_write)


def _warmup_numba_dp() -> None:
    """Trigger Numba JIT compilation with a tiny dummy call.

    Called before Pool() creation so forked workers inherit the compiled
    function from cache rather than recompiling independently.
    """
    if not _NUMBA_AVAILABLE:
        return
    import numpy as np
    from .hp_penalty import _score_hp_dp_numba
    q = np.array([65, 84], dtype=np.uint8)   # "AT"
    r = np.array([65, 84, 65], dtype=np.uint8)  # "ATA"
    dc = np.array([0.5, 1.0, 0.5], dtype=np.float64)
    ic = np.array([1.25, 1.25], dtype=np.float64)
    _score_hp_dp_numba(q, r, dc, ic)


# ---------------------------------------------------------------------------
# Parallel worker state (populated by refine_bam_junctions before Pool fork)
# ---------------------------------------------------------------------------
# On Linux the default multiprocessing start method is 'fork'.  Worker
# processes inherit the parent's memory via copy-on-write, so large objects
# (genome dict, junctions_idx, penalty_table) are shared at zero cost without
# pickling.  _WORKER_POOL_STATE is populated in the parent before Pool() is
# created and cleared after the pool exits.

_WORKER_POOL_STATE: dict = {}


def _refine_read_batch(sam_strings: List[str]) -> List[Tuple[str, List]]:
    """Process a batch of N-op SAM records in a worker process.

    Reads *sam_strings*, calls :func:`refine_read_junctions` on each, and
    returns ``(sam_str, replacements)`` pairs.  All shared state
    (junctions_idx, annotated_set, genome, header, scoring kwargs) is
    inherited from the parent via fork() and stored in
    :data:`_WORKER_POOL_STATE`.
    """
    state = _WORKER_POOL_STATE
    header = state['header']
    junctions_idx = state['junctions_idx']
    annotated_set = state['annotated_set']
    genome = state['genome']
    kw = state['kwargs']
    penalty_table_set: Optional[PenaltyTableSet] = state.get('penalty_table_set')
    profile_enabled = bool(state.get('profile_enabled', False))
    profile_sample_rate = max(1, int(state.get('profile_sample_rate', 1) or 1))
    profile = JunctionRefineProfile(profile_sample_rate) if profile_enabled else None

    results: List[Tuple[str, List]] = []
    for i, sam_str in enumerate(sam_strings):
        try:
            _t_parse = time.perf_counter() if profile is not None else 0.0
            read = pysam.AlignedSegment.fromstring(sam_str, header)
            _profile_time(profile, 'worker_sam_parse', _t_parse)
            chrom = standardize_chrom_name(read.reference_name)
            genome_seq = genome.get(chrom, '')
            if not genome_seq:
                results.append((sam_str, []))
                continue
            strand = '-' if read.is_reverse else '+'
            if penalty_table_set is not None:
                eff_kw = {**kw, 'penalty_table': penalty_table_set.for_read(read)}
            else:
                eff_kw = kw
            if profile is not None and (i % profile_sample_rate == 0):
                eff_kw = {**eff_kw, 'profile': profile}
            replacements = refine_read_junctions(
                read, junctions_idx, annotated_set, genome_seq, strand, **eff_kw
            )
            results.append((sam_str, replacements))
        except Exception:
            results.append((sam_str, []))
            if profile is not None:
                profile.inc('worker_errors')
    if profile is not None:
        return {'results': results, 'profile': profile.to_raw_dict()}
    return results


# ---------------------------------------------------------------------------
# Batch BAM refinement
# ---------------------------------------------------------------------------

def refine_bam_junctions(
    input_bam: str,
    output_bam: str,
    aligner_bams: List[str],
    annotated_junctions: Set[Tuple],
    genome: Dict[str, str],
    hp_pen: float = 0.25,
    W: int = 15,
    max_slide: int = 10,
    search_radius: int = 5000,
    max_boundary_shift: int = 50,
    boundary_error_window: int = 10,
    max_junction_size: Optional[int] = None,
    max_candidates_per_nop: Optional[int] = None,
    sort_and_index: bool = True,
    penalty_table_path: Optional[str] = None,
    str_penalty_table_path: Optional[str] = None,
    prebuilt_junction_pool: Optional[Set] = None,
    prebuilt_annotated_set: Optional[Set] = None,
    sort_threads: int = 1,
    n_workers: int = 1,
    batch_size: int = 200,
    penalty_table_set: Optional['PenaltyTableSet'] = None,
    profile_path: Optional[str] = None,
    profile_sample_rate: int = 1,
    motif_blind: bool = False,
    hold_margin: float = 0.0,
    hp_drift_margin: float = 0.0,
    hp_drift_min_run: int = 4,
    microhom_drift_margin: float = 0.0,
    microhom_threshold: float = 0.5,
    drift_near_tie_cap: float = 0.0,
    drift_positional_gate: float = 0.0,
) -> Dict[str, int]:
    """Refine all N-op junctions in a BAM file.

    Writes a new BAM with improved N-op boundaries.  Reads without N-ops,
    or where no better junction is found, are passed through unchanged.

    Args:
        input_bam:            Path to input consensus BAM.
        output_bam:           Path to write refined BAM.
        aligner_bams:         Per-aligner BAM paths for junction pool.
        annotated_junctions:  From ``load_annotated_junctions()``.
        genome:               Dict mapping chrom → sequence.
        hp_pen:               Homopolymer penalty (tunable).
        W:                    Retained for API compatibility; unused by the
                              current HP-anchored semi-global implementation.
        max_slide:            Retained for API compatibility; unused by the
                              current HP-anchored semi-global implementation.
        max_boundary_shift:   Max allowed shift of either intron boundary (bp).
                              Prevents false-positive matches from junctions
                              in adjacent genes within search_radius.
        search_radius:        Junction search radius (bp).
        max_junction_size:    Optional maximum observed/candidate junction
                              length.  Applied when building a pool from BAMs
                              and when querying a pre-built pool.
        max_candidates_per_nop:
                              Optional deterministic cap on candidates scored
                              per N-op after candidate ranking.
        sort_and_index:       Sort and index the output BAM when True.
        penalty_table_path:   Optional path to ``penalty_scores.tsv`` produced
                              by ``empirical_cigar_error_profiler.py``.  When
                              provided, overrides the heuristic del/ins cost
                              step-function with empirical per-HP-length values.
                              Ignored when *penalty_table_set* is provided.
        penalty_table_set:    Optional :class:`PenaltyTableSet` holding
                              per-UMI-bin tables.  When provided, each read's
                              UMI-count tag (default ``XC``) is read to select
                              the appropriate table.  Takes precedence over
                              *penalty_table_path*.

    Returns:
        Stats dict with keys: total, n_op_reads, refined, unchanged, errors.
    """
    profile = JunctionRefineProfile(profile_sample_rate) if profile_path else None
    penalty_table: Optional[HpPenaltyTable] = None
    if penalty_table_path:
        _t_penalty = time.perf_counter() if profile is not None else 0.0
        try:
            penalty_table = HpPenaltyTable.from_tsv(penalty_table_path, str_path=str_penalty_table_path)
            logger.info(
                "refine_bam_junctions: loaded empirical penalty table from %s",
                penalty_table_path,
            )
        except Exception as exc:
            logger.warning(
                "refine_bam_junctions: failed to load penalty table from %s: %s "
                "— falling back to heuristic scoring",
                penalty_table_path, exc,
            )
        _profile_time(profile, 'penalty_table_load', _t_penalty)
    stats = dict(total=0, n_op_reads=0, refined=0, unchanged=0, errors=0)

    # Build junction pool and index.
    # When prebuilt_junction_pool is provided (from `rectify prescan`), use it
    # directly and skip BAM collection — used for chunked correction pipelines.
    if prebuilt_junction_pool is not None:
        _t_pool = time.perf_counter() if profile is not None else 0.0
        all_junctions = prebuilt_junction_pool
        annotated_set = prebuilt_annotated_set if prebuilt_annotated_set is not None else set()
        logger.info(
            "refine_bam_junctions: using pre-built pool (%d junctions, %d annotated)",
            len(all_junctions), len(annotated_set),
        )
        _profile_time(profile, 'junction_pool_load_or_assign', _t_pool)
    else:
        _t_pool = time.perf_counter() if profile is not None else 0.0
        all_junctions, annotated_set = build_junction_pool(
            aligner_bams,
            annotated_junctions,
            max_junction_size=max_junction_size,
        )
        logger.info(
            "refine_bam_junctions: pool has %d junctions (%d annotated)",
            len(all_junctions), len(annotated_set),
        )
        _profile_time(profile, 'junction_pool_build', _t_pool)
    _t_index = time.perf_counter() if profile is not None else 0.0
    junctions_idx = _build_junction_index(all_junctions)
    _profile_time(profile, 'junction_index_build', _t_index)
    if profile is not None:
        profile.inc('pool_junctions', len(all_junctions))
        profile.inc('pool_annotated_junctions', len(annotated_set))

    if n_workers > 1:
        _run_parallel(
            input_bam, output_bam, genome, junctions_idx, annotated_set, stats,
            hp_pen, W, max_slide, search_radius, max_boundary_shift,
            boundary_error_window, max_junction_size, max_candidates_per_nop,
            penalty_table, n_workers, batch_size,
            penalty_table_set=penalty_table_set, motif_blind=motif_blind,
            hold_margin=hold_margin, hp_drift_margin=hp_drift_margin,
            hp_drift_min_run=hp_drift_min_run, profile=profile,
            microhom_drift_margin=microhom_drift_margin,
            microhom_threshold=microhom_threshold,
            drift_near_tie_cap=drift_near_tie_cap,
            drift_positional_gate=drift_positional_gate,
        )
    else:
        _run_sequential(
            input_bam, output_bam, genome, junctions_idx, annotated_set, stats,
            hp_pen, W, max_slide, search_radius, max_boundary_shift,
            boundary_error_window, max_junction_size, max_candidates_per_nop,
            penalty_table,
            penalty_table_set=penalty_table_set, motif_blind=motif_blind,
            hold_margin=hold_margin, hp_drift_margin=hp_drift_margin,
            hp_drift_min_run=hp_drift_min_run, profile=profile,
            microhom_drift_margin=microhom_drift_margin,
            microhom_threshold=microhom_threshold,
            drift_near_tie_cap=drift_near_tie_cap,
            drift_positional_gate=drift_positional_gate,
        )

    if sort_and_index:
        try:
            _t_sort = time.perf_counter() if profile is not None else 0.0
            _sort_and_index(output_bam, n_threads=sort_threads)
            _profile_time(profile, 'sort_and_index_output_bam', _t_sort)
        except Exception as exc:
            # Do NOT swallow this: an unsorted/unindexed output_bam is not a
            # usable refined BAM. A caller that promotes output_bam to its
            # "current" BAM on a normal return (e.g. correct_command.py's
            # Module 2H step) would silently carry that broken file forward,
            # surfacing as an unrelated-looking failure much later. Log at
            # ERROR (the debuggable moment) and re-raise so this failure is
            # attributed to its real cause, not lost.
            logger.error(
                "refine_bam_junctions: sort/index failed for %s: %s",
                output_bam, exc,
            )
            raise RuntimeError(
                f"refine_bam_junctions: sort/index failed for output BAM "
                f"{output_bam!r}"
            ) from exc

    logger.info(
        "refine_bam_junctions done: %d total, %d with N-ops, %d refined, %d unchanged, %d errors",
        stats['total'], stats['n_op_reads'], stats['refined'],
        stats['unchanged'], stats['errors'],
    )
    if profile is not None:
        profile.counts.update({f"final_stats_{k}": int(v) for k, v in stats.items()})
        summary = profile.to_summary()
        out_path = Path(profile_path)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        with open(out_path, 'w') as fh:
            json.dump(summary, fh, indent=2, sort_keys=True)
        logger.info("refine_bam_junctions: wrote profile summary to %s", out_path)
    return stats


def _sort_and_index(bam_path: str, n_threads: int = 1) -> None:
    """Sort and index a BAM file using samtools via subprocess.

    Uses subprocess (not pysam.sort/pysam.index) to avoid heap corruption
    bugs in pysam's C-level sort on CentOS 7 / older glibc.

    Args:
        bam_path:  Path to the BAM file to sort and index in place.
        n_threads: Number of threads to pass to ``samtools sort`` and
                   ``samtools index`` via ``-@``.  Defaults to 1.

    Raises:
        FileNotFoundError: If samtools cannot be located on PATH or in the
            active conda/venv environment's bin directory.
    """
    import os
    import shutil
    import subprocess
    import sys

    # Resolve samtools: check PATH first, then the conda/venv env bin dir
    # that contains the current Python interpreter (robust across platforms
    # where correction job scripts may not export the full conda PATH).
    samtools = shutil.which('samtools')
    if samtools is None:
        candidate = os.path.join(os.path.dirname(sys.executable), 'samtools')
        if os.path.isfile(candidate) and os.access(candidate, os.X_OK):
            samtools = candidate
    if samtools is None:
        raise FileNotFoundError(
            "samtools not found on PATH or in the active environment "
            f"({os.path.dirname(sys.executable)}). "
            "Add samtools to PATH or install it into the rectify conda env."
        )

    tmp = bam_path + '.tmp.bam'
    subprocess.run(
        [samtools, 'sort', f'-@{n_threads}', '-o', tmp, bam_path],
        check=True, capture_output=True,
    )
    os.replace(tmp, bam_path)
    subprocess.run(
        [samtools, 'index', f'-@{n_threads}', bam_path],
        check=True, capture_output=True,
    )


# ---------------------------------------------------------------------------
# Tuning harness
# ---------------------------------------------------------------------------

def evaluate_hp_pen_values(
    input_bam: str,
    aligner_bams: List[str],
    annotated_junctions: Set[Tuple],
    genome: Dict[str, str],
    ground_truth_junctions: List[Tuple[str, int, int]],
    hp_pen_values: Optional[List[float]] = None,
    W: int = 15,
    max_slide: int = 10,
    search_radius: int = 5000,
) -> List[Dict]:
    """Evaluate multiple hp_pen values against a ground-truth junction set.

    For each hp_pen, counts:
    - true_positive:  correct reads that stay at the ground-truth junction
    - false_negative: correct reads incorrectly moved away
    - true_corrected: reads with wrong N-ops moved to ground-truth
    - false_corrected: reads with wrong N-ops moved to a different wrong junction

    Args:
        input_bam:               Consensus BAM to evaluate.
        aligner_bams:            Per-aligner BAMs for pool construction.
        annotated_junctions:     Full annotated junction set.
        genome:                  Chromosome sequences.
        ground_truth_junctions:  List of (chrom, intron_start, intron_end).
        hp_pen_values:           List of penalty values to test.
        W, max_slide, search_radius: Scoring parameters.

    Returns:
        List of result dicts, one per hp_pen value.
    """
    if hp_pen_values is None:
        hp_pen_values = [0.1, 0.2, 0.25, 0.3, 0.4, 0.5, 0.75, 1.0]

    all_junctions, annotated_set = build_junction_pool(aligner_bams, annotated_junctions)
    junctions_idx = _build_junction_index(all_junctions)
    gt_set = set((c, s, e) for c, s, e in ground_truth_junctions)

    results = []
    for pen in hp_pen_values:
        tp = fn = tc = fc = no_n = 0
        delta_distribution: Dict[int, int] = {}

        with pysam.AlignmentFile(input_bam, 'rb') as bam:
            for read in bam:
                if read.is_unmapped or not read.cigartuples:
                    continue
                n_ops = [(ns, ne) for _, ns, ne in [
                    (i, r, r + l)
                    for i, (op, l) in enumerate(read.cigartuples)
                    for r in [_n_op_ref_start(read, i)]
                    if op == _N
                ]]
                if not n_ops:
                    no_n += 1
                    continue

                strand = '-' if read.is_reverse else '+'
                chrom = standardize_chrom_name(read.reference_name)
                genome_seq = genome.get(chrom, '')
                if not genome_seq:
                    continue

                replacements = refine_read_junctions(
                    read, junctions_idx, annotated_set, genome_seq, strand,
                    hp_pen=pen, W=W, max_slide=max_slide,
                    search_radius=search_radius,
                )

                rep_map = {(old_ns, old_ne): (new_ns, new_ne)
                           for _, old_ns, old_ne, new_ns, new_ne in replacements}

                for ns, ne in n_ops:
                    currently_gt = (chrom, ns, ne) in gt_set
                    if (ns, ne) in rep_map:
                        new_ns, new_ne = rep_map[(ns, ne)]
                        delta = (new_ns - ns) + (new_ne - ne)
                        delta_distribution[delta] = delta_distribution.get(delta, 0) + 1
                        if (chrom, new_ns, new_ne) in gt_set:
                            tc += 1
                        else:
                            fc += 1
                    else:
                        if currently_gt:
                            tp += 1
                        # wrong junction not corrected: counted in analysis separately

        results.append({
            'hp_pen': pen,
            'true_positive': tp,
            'false_negative': fn,
            'true_corrected': tc,
            'false_corrected': fc,
            'delta_distribution': delta_distribution,
        })
        logger.info(
            "hp_pen=%.2f: TP=%d FN=%d TC=%d FC=%d",
            pen, tp, fn, tc, fc,
        )

    return results


def _n_op_ref_start(read: pysam.AlignedSegment, target_idx: int) -> int:
    """Return reference position at start of N-op at cigar index target_idx.

    Cursor walker — advances on ``_REF_CONSUMING_POS`` so preceding introns are
    counted (ISSUE-004).
    """
    pos = read.reference_start
    for i, (op, length) in enumerate(read.cigartuples):
        if i == target_idx:
            return pos
        if op in _REF_CONSUMING_POS:
            pos += length
    return pos
